name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-format clang-tidy cmake build-essential doxygen grap
          pip install conan

      - name: Run clang-format
        run: |
          find include src examples -name '*.cpp' -o -name '*.h' | xargs clang-format -i

      - name: Run build.sh
        run: |
          chmod +x ./build.sh
          conan profile detect
          ./build.sh

      - name: Run clang-tidy
        run: |
          cd build
          make tidy

      - name: Set up Python (for ghp-import)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ghp-import
        run: pip install ghp-import

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f build_docs/
